DROP TABLE IF EXISTS choices;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS contexts;
DROP TABLE IF EXISTS sets;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS visibility;
DROP TYPE IF EXISTS difficulty;
DROP TYPE IF EXISTS question_type;
