# ---- Build Stage ----
FROM golang:1.24-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o onlyexams-prod .


FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /build/onlyexams-prod .

USER nonroot:nonroot
ENTRYPOINT ["./onlyexams-prod"]
