// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: jigao_ai.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JigaoAI_GenerateQuestions_FullMethodName = "/jigao_ai.JigaoAI/GenerateQuestions"
)

// JigaoAIClient is the client API for JigaoAI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JigaoAIClient interface {
	GenerateQuestions(ctx context.Context, in *GenerateQuestionsRequest, opts ...grpc.CallOption) (*GenerateQuestionsResponse, error)
}

type jigaoAIClient struct {
	cc grpc.ClientConnInterface
}

func NewJigaoAIClient(cc grpc.ClientConnInterface) JigaoAIClient {
	return &jigaoAIClient{cc}
}

func (c *jigaoAIClient) GenerateQuestions(ctx context.Context, in *GenerateQuestionsRequest, opts ...grpc.CallOption) (*GenerateQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateQuestionsResponse)
	err := c.cc.Invoke(ctx, JigaoAI_GenerateQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JigaoAIServer is the server API for JigaoAI service.
// All implementations must embed UnimplementedJigaoAIServer
// for forward compatibility.
type JigaoAIServer interface {
	GenerateQuestions(context.Context, *GenerateQuestionsRequest) (*GenerateQuestionsResponse, error)
	mustEmbedUnimplementedJigaoAIServer()
}

// UnimplementedJigaoAIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJigaoAIServer struct{}

func (UnimplementedJigaoAIServer) GenerateQuestions(context.Context, *GenerateQuestionsRequest) (*GenerateQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateQuestions not implemented")
}
func (UnimplementedJigaoAIServer) mustEmbedUnimplementedJigaoAIServer() {}
func (UnimplementedJigaoAIServer) testEmbeddedByValue()                 {}

// UnsafeJigaoAIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JigaoAIServer will
// result in compilation errors.
type UnsafeJigaoAIServer interface {
	mustEmbedUnimplementedJigaoAIServer()
}

func RegisterJigaoAIServer(s grpc.ServiceRegistrar, srv JigaoAIServer) {
	// If the following call pancis, it indicates UnimplementedJigaoAIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JigaoAI_ServiceDesc, srv)
}

func _JigaoAI_GenerateQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JigaoAIServer).GenerateQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JigaoAI_GenerateQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JigaoAIServer).GenerateQuestions(ctx, req.(*GenerateQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JigaoAI_ServiceDesc is the grpc.ServiceDesc for JigaoAI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JigaoAI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jigao_ai.JigaoAI",
	HandlerType: (*JigaoAIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateQuestions",
			Handler:    _JigaoAI_GenerateQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jigao_ai.proto",
}
