// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: jigao_ai.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      int32                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Instructions  string                 `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	QuestionType  string                 `protobuf:"bytes,4,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionsRequest) Reset() {
	*x = GenerateQuestionsRequest{}
	mi := &file_jigao_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsRequest) ProtoMessage() {}

func (x *GenerateQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jigao_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_jigao_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateQuestionsRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GenerateQuestionsRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *GenerateQuestionsRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *GenerateQuestionsRequest) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

type GenerateQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*GeneratedQuestions  `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionsResponse) Reset() {
	*x = GenerateQuestionsResponse{}
	mi := &file_jigao_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsResponse) ProtoMessage() {}

func (x *GenerateQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jigao_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_jigao_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateQuestionsResponse) GetQuestions() []*GeneratedQuestions {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GenerateQuestionsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GeneratedQuestions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Choices       []*Choice              `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`
	Answer        *Answer                `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedQuestions) Reset() {
	*x = GeneratedQuestions{}
	mi := &file_jigao_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedQuestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedQuestions) ProtoMessage() {}

func (x *GeneratedQuestions) ProtoReflect() protoreflect.Message {
	mi := &file_jigao_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedQuestions.ProtoReflect.Descriptor instead.
func (*GeneratedQuestions) Descriptor() ([]byte, []int) {
	return file_jigao_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratedQuestions) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *GeneratedQuestions) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *GeneratedQuestions) GetAnswer() *Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Difficulty    string                 `protobuf:"bytes,1,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	QuestionType  string                 `protobuf:"bytes,2,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_jigao_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_jigao_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_jigao_ai_proto_rawDescGZIP(), []int{3}
}

func (x *Question) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Question) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *Question) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChoiceText    string                 `protobuf:"bytes,1,opt,name=choice_text,json=choiceText,proto3" json:"choice_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_jigao_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_jigao_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_jigao_ai_proto_rawDescGZIP(), []int{4}
}

func (x *Choice) GetChoiceText() string {
	if x != nil {
		return x.ChoiceText
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Explanation   string                 `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_jigao_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_jigao_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_jigao_ai_proto_rawDescGZIP(), []int{5}
}

func (x *Answer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Answer) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_jigao_ai_proto protoreflect.FileDescriptor

const file_jigao_ai_proto_rawDesc = "" +
	"\n" +
	"\x0ejigao_ai.proto\x12\bjigao_ai\"\x99\x01\n" +
	"\x18GenerateQuestionsRequest\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\"\n" +
	"\finstructions\x18\x03 \x01(\tR\finstructions\x12#\n" +
	"\rquestion_type\x18\x04 \x01(\tR\fquestionType\"m\n" +
	"\x19GenerateQuestionsResponse\x12:\n" +
	"\tquestions\x18\x01 \x03(\v2\x1c.jigao_ai.GeneratedQuestionsR\tquestions\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x9a\x01\n" +
	"\x12GeneratedQuestions\x12.\n" +
	"\bquestion\x18\x01 \x01(\v2\x12.jigao_ai.QuestionR\bquestion\x12*\n" +
	"\achoices\x18\x02 \x03(\v2\x10.jigao_ai.ChoiceR\achoices\x12(\n" +
	"\x06answer\x18\x03 \x01(\v2\x10.jigao_ai.AnswerR\x06answer\"k\n" +
	"\bQuestion\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x01 \x01(\tR\n" +
	"difficulty\x12#\n" +
	"\rquestion_type\x18\x02 \x01(\tR\fquestionType\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\")\n" +
	"\x06Choice\x12\x1f\n" +
	"\vchoice_text\x18\x01 \x01(\tR\n" +
	"choiceText\"B\n" +
	"\x06Answer\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation2i\n" +
	"\aJigaoAI\x12^\n" +
	"\x11GenerateQuestions\x12\".jigao_ai.GenerateQuestionsRequest\x1a#.jigao_ai.GenerateQuestionsResponse\"\x00B/Z-github.com/rafidoth/onlyexams/proto/;jigao_aib\x06proto3"

var (
	file_jigao_ai_proto_rawDescOnce sync.Once
	file_jigao_ai_proto_rawDescData []byte
)

func file_jigao_ai_proto_rawDescGZIP() []byte {
	file_jigao_ai_proto_rawDescOnce.Do(func() {
		file_jigao_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jigao_ai_proto_rawDesc), len(file_jigao_ai_proto_rawDesc)))
	})
	return file_jigao_ai_proto_rawDescData
}

var file_jigao_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_jigao_ai_proto_goTypes = []any{
	(*GenerateQuestionsRequest)(nil),  // 0: jigao_ai.GenerateQuestionsRequest
	(*GenerateQuestionsResponse)(nil), // 1: jigao_ai.GenerateQuestionsResponse
	(*GeneratedQuestions)(nil),        // 2: jigao_ai.GeneratedQuestions
	(*Question)(nil),                  // 3: jigao_ai.Question
	(*Choice)(nil),                    // 4: jigao_ai.Choice
	(*Answer)(nil),                    // 5: jigao_ai.Answer
}
var file_jigao_ai_proto_depIdxs = []int32{
	2, // 0: jigao_ai.GenerateQuestionsResponse.questions:type_name -> jigao_ai.GeneratedQuestions
	3, // 1: jigao_ai.GeneratedQuestions.question:type_name -> jigao_ai.Question
	4, // 2: jigao_ai.GeneratedQuestions.choices:type_name -> jigao_ai.Choice
	5, // 3: jigao_ai.GeneratedQuestions.answer:type_name -> jigao_ai.Answer
	0, // 4: jigao_ai.JigaoAI.GenerateQuestions:input_type -> jigao_ai.GenerateQuestionsRequest
	1, // 5: jigao_ai.JigaoAI.GenerateQuestions:output_type -> jigao_ai.GenerateQuestionsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jigao_ai_proto_init() }
func file_jigao_ai_proto_init() {
	if File_jigao_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jigao_ai_proto_rawDesc), len(file_jigao_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jigao_ai_proto_goTypes,
		DependencyIndexes: file_jigao_ai_proto_depIdxs,
		MessageInfos:      file_jigao_ai_proto_msgTypes,
	}.Build()
	File_jigao_ai_proto = out.File
	file_jigao_ai_proto_goTypes = nil
	file_jigao_ai_proto_depIdxs = nil
}
