// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/exams/": {
            "get": {
                "description": "Returns exams filtered by set_id (if provided) or all exams for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "List exams",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional set ID to filter exams",
                        "name": "set_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Exam"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Validates input and creates a new exam from a question set",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "Create an exam",
                "parameters": [
                    {
                        "description": "Exam creation payload (start_time in RFC3339 format)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "description": {
                                    "type": "string"
                                },
                                "duration_in_minutes": {
                                    "type": "integer"
                                },
                                "set_id": {
                                    "type": "string"
                                },
                                "start_time": {
                                    "type": "string"
                                },
                                "title": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/exams/q/{exam_id}": {
            "get": {
                "description": "Returns all questions with choices and answers for the specified exam",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "Get questions of an exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exam ID",
                        "name": "exam_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.QuestionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/exams/{exam_id}": {
            "get": {
                "description": "Returns a single exam by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "Get an exam by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exam ID",
                        "name": "exam_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an exam by its ID",
                "tags": [
                    "Exams"
                ],
                "summary": "Delete an exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exam ID",
                        "name": "exam_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/questions/": {
            "get": {
                "description": "Returns all questions with their choices and answers for the specified set",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Get all questions in a set",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set ID to retrieve questions from",
                        "name": "set_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.QuestionResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a single question with choices and answer in the specified set",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Create a question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set ID to add the question to",
                        "name": "set_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Question creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "answer": {
                                    "$ref": "#/definitions/model.Answer"
                                },
                                "choices": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/model.Choice"
                                    }
                                },
                                "question": {
                                    "$ref": "#/definitions/model.Question"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/sets/": {
            "get": {
                "description": "Returns the N most recent sets with their owner information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sets"
                ],
                "summary": "Get recent sets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of recent sets to return",
                        "name": "recent",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.SetWithOwner"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new empty question set owned by the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sets"
                ],
                "summary": "Create a new set",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Set"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/sets/access": {
            "post": {
                "description": "Grants a user shared access to a set",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Sets"
                ],
                "summary": "Grant set access",
                "parameters": [
                    {
                        "description": "Access grant payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "set_id": {
                                    "type": "string"
                                },
                                "user_id": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/sets/access_list/{set_id}": {
            "get": {
                "description": "Returns the list of users (owner + shared) who have access to a set",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sets"
                ],
                "summary": "Get set access list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set ID",
                        "name": "set_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/users.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/sets/{set_id}": {
            "get": {
                "description": "Returns a set with its visibility, title, and context content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sets"
                ],
                "summary": "Get a set by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set ID",
                        "name": "set_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "context": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "string"
                                },
                                "title": {
                                    "type": "string"
                                },
                                "visibility": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the visibility and title of an existing set",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Sets"
                ],
                "summary": "Update a set",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set ID",
                        "name": "set_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Set update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string"
                                },
                                "visibility": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a set and its associated context content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sets"
                ],
                "summary": "Delete a set",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set ID",
                        "name": "set_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "title": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/submissions/{exam_id}": {
            "get": {
                "description": "Returns the evaluation result (score and answer sheet) for the authenticated user's submission to the specified exam",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Submissions"
                ],
                "summary": "Get submission result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exam ID",
                        "name": "exam_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "answer_sheet": {
                                            "type": "object"
                                        },
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "score": {
                                            "type": "integer"
                                        }
                                    }
                                },
                                "message": {
                                    "type": "string"
                                },
                                "success": {
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/": {
            "post": {
                "description": "Inserts a user record if they don't already exist (upsert on first login)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Log in or register a user",
                "parameters": [
                    {
                        "description": "User login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "string"
                                },
                                "image_url": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User logged in successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/v1/users/user": {
            "get": {
                "description": "Returns a user record matching the given email address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get a user by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address of the user",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errs.Action": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/errs.ActionType"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "errs.ActionType": {
            "type": "string",
            "enum": [
                "redirect"
            ],
            "x-enum-varnames": [
                "ActionTypeRedirect"
            ]
        },
        "errs.FieldError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                }
            }
        },
        "errs.HTTPError": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "action to be taken",
                    "allOf": [
                        {
                            "$ref": "#/definitions/errs.Action"
                        }
                    ]
                },
                "code": {
                    "type": "string"
                },
                "errors": {
                    "description": "field level errors",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/errs.FieldError"
                    }
                },
                "message": {
                    "type": "string"
                },
                "override": {
                    "type": "boolean"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "model.Answer": {
            "type": "object",
            "properties": {
                "correct_answer": {
                    "$ref": "#/definitions/model.CorrectAnswer"
                },
                "created_at": {
                    "type": "string"
                },
                "explanation": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "question_id": {
                    "type": "string"
                }
            }
        },
        "model.AnswerResponse": {
            "type": "object",
            "properties": {
                "accepted_answers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "case_sensitive": {
                    "type": "boolean"
                },
                "correct_bool": {
                    "type": "boolean"
                },
                "correct_choice_id": {
                    "type": "string"
                },
                "correct_choice_position": {
                    "type": "integer"
                },
                "explanation": {
                    "type": "string"
                },
                "model_answer": {
                    "type": "string"
                }
            }
        },
        "model.Choice": {
            "type": "object",
            "properties": {
                "choice_text": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "question_id": {
                    "type": "string"
                }
            }
        },
        "model.ChoiceResponse": {
            "type": "object",
            "properties": {
                "choice_id": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "model.CorrectAnswer": {
            "type": "object",
            "properties": {
                "fib_accepted_answers": {
                    "description": "For fill_in_the_blanks",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fib_case_sensitive": {
                    "type": "boolean"
                },
                "mcq_correct_choice_position": {
                    "description": "For multiple_choice_questions (1-indexed position)",
                    "type": "integer"
                },
                "sq_model_answer": {
                    "description": "For short_question",
                    "type": "string"
                },
                "tf_correct_choice": {
                    "description": "For true_false",
                    "type": "boolean"
                }
            }
        },
        "model.Exam": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "$ref": "#/definitions/users.User"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "set": {
                    "$ref": "#/definitions/model.Set"
                },
                "set_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "model.Question": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "question_type": {
                    "type": "string"
                },
                "set_id": {
                    "type": "string"
                }
            }
        },
        "model.QuestionResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "$ref": "#/definitions/model.AnswerResponse"
                },
                "answer_id": {
                    "type": "string"
                },
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ChoiceResponse"
                    }
                },
                "difficulty": {
                    "type": "string"
                },
                "question_id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.Set": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "visibility": {
                    "type": "string"
                }
            }
        },
        "service.SetWithOwner": {
            "type": "object",
            "properties": {
                "owner": {
                    "$ref": "#/definitions/users.User"
                },
                "set": {
                    "$ref": "#/definitions/model.Set"
                }
            }
        },
        "users.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
